### ISSUE TITLE
Calculator not working

### ISSUE THREAD

**Issue by Asjad1245** [pub-calculator-io/scientific-calculator#1]
Hi, I have installed calculator as a plugin on my site and called it in my wordpress post through iframe. but it is not working. Here is a url:
https://www.derekenmachineonline.nl/49-2/

I also tried shortcode method. It also didn't work.

**Comment by irani666** [comment]
Hi i tried it too but not working

**Comment by Asjad1245** [comment]
Is there any solution?

**Comment by irani666** [comment]
Hi! after the plugin activation there is no widget option and even after applying the shortcode the calculator dosent work

**Comment by arolus** [comment]
This has been fixed.
Download and install again to fix.
